name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./Finance_Tracker/messages
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DATABASE: messages_test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: admin
      #POSTGRES_DATABASE: messages_test


    steps:
      - uses: actions/checkout@v4

      # Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./Finance_Tracker/messages
          ruby-version: 3.4
          bundler-cache: true

      # Node
      #- name: Set up Node
       # uses: actions/setup-node@v4
        #with:
         # node-version: 22.18.0
          #cache: yarn

      # System deps
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
        
      #- name: Install gems
       # run: bundle install

      # JS deps
      #- name: Install JS dependencies
        #run: yarn install --frozen-lockfile

      # DB + tests
      - name: Run tests
        env:
          #DATABASE_URL: postgres://postgres:password@localhost:5432/messages_test
          RAILS_ENV: test
          POSTGRES_DATABASE: messages_test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: admin
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |

          bin/rails db:prepare
          bundle exec rspec
